name: TLD Query Generator

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
    inputs:
      tld_count:
        description: 'Number of TLDs to include in the query'
        required: true
        default: '50'
        type: string

jobs:
  generate-query:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Generate Query
      run: |
        python scripts/generate_tld_query.py ${{ github.event.inputs.tld_count }}
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tld_query.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update TLD query" && git push) 