name: TLD Query Generator

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      tld_count:
        description: 'Number of TLDs to include in the query'
        required: true
        default: '50'
        type: string

jobs:
  generate-query:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Generate Query
      run: |
        echo 'import requests
import json
import sys
from datetime import datetime

tld_count = int(sys.argv[1]) if len(sys.argv) > 1 else 50
response = requests.get(f"https://isc.sans.edu/api/domaintop/{tld_count}?json")
data = response.json()
tlds = [item["domain"].split(".")[-1] for item in data]
query = f"""EmailEvents
| where RecipientEmailAddress endswith ({' or '.join(f'"{tld}"' for tld in tlds)})
| summarize count() by RecipientEmailAddress, SenderFromAddress, Subject
| order by count_ desc"""

output = {
    "date": datetime.now().strftime("%Y-%m-%d"),
    "tlds": tlds,
    "query": query
}

with open("tld_query.json", "w") as f:
    json.dump(output, f, indent=2)' > generate_query.py
        python generate_query.py ${{ github.event.inputs.tld_count }}
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tld_query.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update TLD query" && git push) 